// Weekly spelling word lists
// Update these lists weekly with new words

export const wordLists = {
  "Week 1": [
    "occasionally",
    "particularly",
    "definitely",
    "beautiful",
    "necessary",
    "separate",
    "receive",
    "believe",
    "achieve",
    "convenient",
    "environment",
    "government",
    "important",
    "different",
    "difficult",
    "interesting",
    "knowledge",
    "language",
    "business",
    "calendar",
  ],
  "Week 2": [
    "adventure",
    "challenge",
    "discovery",
    "experience",
    "fascinating",
    "generous",
    "happiness",
    "imagination",
    "journey",
    "kindness",
    "laughter",
    "mystery",
    "natural",
    "opportunity",
    "peaceful",
    "question",
    "remember",
    "successful",
    "treasure",
    "wonderful",
  ],
  "Week 3": [
    "accommodate",
    "embarrass",
    "occurrence",
    "recommend",
    "successful",
    "appreciate",
    "experience",
    "independent",
    "opportunity",
    "responsible",
    "communication",
    "environment",
    "immediately",
    "occasionally",
    "particularly",
    "accomplish",
    "determine",
    "influence",
    "maintenance",
    "perspective",
  ],
  "Common Words": [
    "because",
    "through",
    "thought",
    "though",
    "enough",
    "friend",
    "people",
    "school",
    "should",
    "would",
    "could",
    "might",
    "right",
    "write",
    "their",
    "there",
    "they're",
    "where",
    "were",
    "we're",
  ],
};

// Default word list (for backward compatibility)
export const defaultWordList = wordLists["Week 1"];
